username=input("Имя пользователя:")
title=input("Заголовок заметки:")
content= input("описание заметки:")
status= input("статус заметки:")
created_date=input("дата создания заметки в формате 'день-месяц-год':")
issue_date= input("Дата истечения заметки в формате 'день-месяц-год':")
title1=input("Ввести первый заголовок:")
title2=input("Ввести второй заголовок:")
title3=input("Ввести третий заголовок:")
titles=[title1,title2,title3]
print("Имя пользователя:",username)
print("Заголовок заметки:",title)
print("Описание заметки:", content)
print("Статус заметки:", status)
print("Дата создания заметки:", created_date)
print("Дата истечения заметки:", issue_date)
